### ISSUE TITLE
Autoreplacement with blank match causes everything to be replaced with it

### ISSUE THREAD

**Issue by nylim11** [TheoTech/spf.io#1]
Note from user:
"If a word is added to autoreplacements without any "Matches", the captioner will replace EVERYTHING with that word. 
You can reproduce this by adding a word (without a match), closing and reopening the beta captioner, and then opening a trace. Someone had added "potluckers" to our autoreplacement dictionary a few weeks ago and when I started my training it took me a while to figure out why the editor was filled with this word even though the red text initially seemed to be captioning the sermon correctly."

**Comment by chrislim** [comment]
The next release will include a fix for this.

**Comment by chrislim** [comment]
This issue is resolved in the latest release.
