### ISSUE TITLE
Dates not shown in Planning Center integration

### ISSUE THREAD

**Issue by CameronDevine** [TheoTech/spf.io#10]
When importing plans from Planning Center if a title for the service is not shown it is close to impossible to tell which one to choose, see below. Could the date for each plan also be shown in this menu?

![image](https://user-images.githubusercontent.com/10394896/45924925-4a0a7e00-bec0-11e8-89ef-e8d9b4c4375b.png)

**Comment by chrislim** [comment]
Which attribute(s) would you like? For example "short_dates"?

![image](https://user-images.githubusercontent.com/469630/45963622-6699d980-bfd8-11e8-83d2-b45373734b3d.png)

**Comment by CameronDevine** [comment]
I think converting the `sort_date` into the correct format depending on locale would be a good method.

**Comment by chrislim** [comment]
Alright, the latest version will now show a formatted sort_date.
