### ISSUE TITLE
Red text is sent and copied to the next line when <tab> pressed

### ISSUE THREAD

**Issue by CameronDevine** [TheoTech/spf.io#11]
This Sunday and last Sunday I noticed that when I press the Tab key any red text in the beta captioner is sent and also copied to the next line.

**Comment by CameronDevine** [comment]
This issue can be seen in the history of the session at OPPC this Sunday in the utterances sent at `17:06:21` and `17:06:33`. In the first utterance I pressed tab after the word "name" turned black, however a few words appear after "name" and are repeated in the second utterance.

**Comment by CameronDevine** [comment]
This problem did not occur using a different mac laptop at the Seattle Presbytery meeting today.

**Comment by chrislim** [comment]
Just to clarify, did you mean that it did happen again? Or that it didn't?

**Comment by CameronDevine** [comment]
This Sunday I will have a chance to test if this is still an issue with the hardware/software configuration at OPPC. Using EJ's laptop at the Presbytery meeting tonight I did not have this issue.

**Comment by CameronDevine** [comment]
This is still an issue when using OPPC's laptop.

**Comment by chrislim** [comment]
Ok. We're pushing out an update this week that changes a few things and I'd like to see if it addresses it.

**Comment by chrislim** [comment]
Just pushed an update today to address this.
