### ISSUE TITLE
Cannot release manually entered text in the beta captioner

### ISSUE THREAD

**Issue by chrislim** [TheoTech/spf.io#13]
When using the beta captioner, editing and releasing the output of the captioner works, but releasing text you have manually entered into the editor does not work (i.e. the text is not released to the audience).

This was a regression introduced when we fixed issue #11 to prevent the release of volatile red text.

**Comment by chrislim** [comment]
We did solve issue #11 successfully, but only tested that it met the issue's requirements. We did not test manual typing, which is what broke as a result of the fix.

In the future, we need to have a beta captioner test checklist or automated test suite that tests manual typing, captioned output, edited captioned output, translation, raw caption streaming, and releasing from remote input.

**Comment by CameronDevine** [comment]
I have done a little bit of work with [Selenium](https://www.seleniumhq.org/) in the past. It allows you to write scripts in a number of different languages to automate clicks and typing in a web browser. I haven't tried it, but there are also [services](https://saucelabs.com/) which allow you to run tests on many different OS/browser combinations at once. These tools can even be integrated with continuous integration services such as [Travis CI](https://docs.travis-ci.com/user/gui-and-headless-browsers/).

**Comment by chrislim** [comment]
Thanks for the ideas! We've started to try using [puppeteer](https://github.com/GoogleChrome/puppeteer) for the UI test automation, but unfortunately the tests are rather brittle and it's been kind of messy. I think I may need to refactor the editor itself so that each individual interaction can be unit tested (w/o the UI input) and then we can integration test with a single UI based input method as a smoke test.

**Comment by chrislim** [comment]
I'm closing this ticket for now because the latest release has resolved this issue.
