### ISSUE TITLE
Beta Captioner send utterance from document stopped working

### ISSUE THREAD

**Issue by CameronDevine** [TheoTech/spf.io#14]
This Sunday I had an issue where midway through the service the Beta Captioner would no longer let me send an utterance from a document by selecting it and pressing tab. This was fixed by refreshing the beta captioner page.

**Comment by chrislim** [comment]
Were you able to notice any errors in the inspector/console?

**Comment by CameronDevine** [comment]
No, it was in the middle of the service so I wanted to get it working again as soon as possible.

**Comment by chrislim** [comment]
I'm having trouble reproducing the error. Do you remember any other contextual information that may help me do so?

**Comment by CameronDevine** [comment]
I'm sorry, I don't. If it happens again I will try to get more information for you.

**Comment by chrislim** [comment]
Okay, thanks!
