### ISSUE TITLE
All plans not shown with Planning Center integration

### ISSUE THREAD

**Issue by CameronDevine** [TheoTech/spf.io#16]
When I was preparing the playlist for this Sunday's service I was not able to find the correct plan to import in the Planning Center integration.

![image](https://user-images.githubusercontent.com/10394896/48326756-e06d3d00-e5ef-11e8-90fd-af0599129cbc.png)

Looking back in Planning Center I do not believe that all of these plans were actually edited 3 days ago. I checked one the 6/11/17 plan and it did not appear to have been edited anytime after the service.

**Comment by chrislim** [comment]
I checked the results coming back from planning center and the last updated date field that we get back from the server seem to be indeed 3 days ago, so there may have been a change that affected them all.

In any case, in the next release I've changed it to show you the last 25 plans by sort_date instead. That way you can see what's coming up.

**Comment by CameronDevine** [comment]
That sounds like a good fix. Thanks.
