### ISSUE TITLE
Auth expiration is not obvious when beta captioner is opened for a long time

### ISSUE THREAD

**Issue by nylim11** [TheoTech/spf.io#2]
Note from user:
" If the beta captioner has been open for a while, you can't open traces. A message will be displayed saying "Loading simulation..." but nothing will happen after that. 
The underlying error is a 403 (Permission Denied), due to some auth expiration. Closing and reopening the captioner fixes the issue, but nothing is displayed to the user to help them realize this is what they need to do. 
Full error:

AccessDeniedRequest has expired2018-06-10T03:54:35Z2018-06-10T03:55:43ZEE7E411313C10F89IXKQUkzumvwNcOca5RkQpAWicT3uMBBn1XP9xzgpGEoFwwskIa0u1rQfWZ7T/SAJHMa+13lTldY="

**Comment by chrislim** [comment]
We check if the user is still logged in every 15 minutes now to mitigate this issue.
