### ISSUE TITLE
Allow audience to activate channels is not working in March 5th, 2019 release

### ISSUE THREAD

**Issue by chrislim** [TheoTech/spf.io#21]
It may not be getting the target/activate channel event.

**Comment by chrislim** [comment]
We changed the client type from "interpreter" to "captioner" which is why it wasn't getting the event.

**Comment by CameronDevine** [comment]
Will this be fixed in time for Ash Wednesday services?

**Comment by chrislim** [comment]
We haven't pushed the full release to production yet. I tested the old release and it's still working. And I have a fix for this in the new release as well.

**Comment by chrislim** [comment]
Latest release resolves this issue.
