### ISSUE TITLE
Autoreplacements replaces strings in the middle of words

### ISSUE THREAD

**Issue by camillemarie** [TheoTech/spf.io#22]
**Repro steps**
1. Add an auto-replacement: lee => ly
2. Start the captioner 
3. Say a sentence containing "Sleep" or "sleeping"
     - "I wasn't sleeping a whole lot"
     - "Walk with me. Eat with me. Sleep when I sleep."

**Expected result:**
The word "Sleep" is unchanged by the autoreplacement of "lee" => "ly"

**Actual result**
"Sleep" is replaced with "Slyp"
     - "I wasn't slyping a whole lot"
     - "Walk with me. Eat with me. Slyp when I slyp."

**Comment by nylim11** [comment]
I was able to reproduce this issue, we'll root cause this and get back to you on an ETA for a potential fix.

**Comment by chrislim** [comment]
I plan to get a fix out by next Sunday. By the way I saw this error come up today, any issues/symptoms appear related to it? 

TypeError: f(...)[e].onrelease is not a function at Object.onrelease (/dist/captioner.1b023e6.js:6:53177) at Object.onrelease (/dist/captioner.1b023e6.js:6:36725) at None (/dist/captioner.1b023e6.js:37:86332) at i (/dist/captioner.1b023e6.js:37:85652) at c (/dist/captioner.1b023e6.js:37:85994) ... (5 additional frame(s) were not displayed)

**Comment by camillemarie** [comment]
> By the way I saw this error come up today, any issues/symptoms appear related to it?
> 
> TypeError: f(...)[e].onrelease is not a function at Object.onrelease (/dist/captioner.1b023e6.js:6:53177) at Object.onrelease (/dist/captioner.1b023e6.js:6:36725) at None (/dist/captioner.1b023e6.js:37:86332) at i (/dist/captioner.1b023e6.js:37:85652) at c (/dist/captioner.1b023e6.js:37:85994) ... (5 additional frame(s) were not displayed)

The person who was running spf.io last Sunday said that everything from the "playlist" unexpectedly posted to the audience view as soon as he opened the captioner. It's the only abnormal thing he noticed. (We also had occasional lag, but I wouldn't expect that to cause a javascript error)

**Comment by chrislim** [comment]
The original autoreplacement issue should be resolved now.
For the release of everything from the "playlist" issue, could you open a new ticket with the steps to reproduce it?

Thanks!
