### ISSUE TITLE
Document title displayed to audience when captioner starts

### ISSUE THREAD

**Issue by camillemarie** [TheoTech/spf.io#25]
**Repro steps:**
1. Create a new session
2. Add a playlist to your session
3. Start the beta captioner
4. Press any key inside the captioner window

**Expected results:**
Nothing should display in the audience view (yet).
The title of a document should never be displayed.

**Actual results:**
The title of the first document in the playlist will appear in the audience view

**console output:**
[quest.spf.io-1555272626234.log](https://github.com/TheoTech/spf.io/files/3130024/quest.spf.io-1555272626234.log)

**Comment by CameronDevine** [comment]
I have noticed this before as well, but never bothered reporting it.

**Comment by chrislim** [comment]
Ok, so sounds like there are two issues. One is the display of document title. The other is that when nothing has been released why is the audience switching to a view where they can see the title.

Is that accurate?

**Comment by camillemarie** [comment]
Sure. My main concern is that _something_ is displayed to audience when nothing has been released yet.

**Comment by chrislim** [comment]
In the latest release something should no longer be displayed when nothing has been released yet.

**Comment by camillemarie** [comment]
Hi Chris,

I'm still seeing the title of the first document displayed in the audience view. Attaching a screenshot to show what it looks like for me. Let me know if you need more details / repro steps.

![image](https://user-images.githubusercontent.com/804366/59163416-d9d77300-8ab5-11e9-9680-e0a3efc241b6.png)

**Comment by chrislim** [comment]
So you would rather have no title whatsoever, just text of what's being said?

**Comment by camillemarie** [comment]
Yep! I'd rather not have a title at all.

Or if there is a title at the top of the session, I'd prefer that it is the title of the session, not the first document from the playlist.

**Comment by CameronDevine** [comment]
At OPPC we often give documents titles such as "Sermon 20190609", which perfectly describes the contents of the document, but isn't great for displaying to an audience.

**Comment by chrislim** [comment]
Working on this now. We're just gonna hide titles.

**Comment by chrislim** [comment]
Latest release should no longer show titles.
