### ISSUE TITLE
Expand Resources tab in Playlist Editor

### ISSUE THREAD

**Issue by CameronDevine** [TheoTech/spf.io#28]
When viewing a playlist the `Resources` tab in the menu on the left is minimized, making it difficult to click the `Documents` button. Multiple times I have clicked on `Resources` when I really should have expanded the `Resources` section then clicked on `Documents`.

**Comment by chrislim** [comment]
So when you're viewing a playlist, you'd like to have the resources menu item expanded? What's the flow of action? Are Documents something you frequently need to go back and forth between in the Playlist view?

**Comment by CameronDevine** [comment]
When I am setting up a spf.io playlist I import the plan from Planning Center, then I start adding existing documents to the playlist. At that point I know what documents I need to create, so I create those documents. Finally, I add those new documents to the playlist.

**Comment by chrislim** [comment]
This issue is addressed in the latest release.

**Comment by CameronDevine** [comment]
Thank you!
