### ISSUE TITLE
Formatting in document editor doesn't match audience view

### ISSUE THREAD

**Issue by CameronDevine** [TheoTech/spf.io#9]
When copy and pasting text with formatting into the document editor sometimes markdown like the following is created,

```markdown
**this is the first line
this is the second line**
```

This renders in the document viewer as,

**this is the first line**
**this is the second line**

However in the audience view this appears as,

**this is the first line**
this is the second line\*\*

In my mind the formatting in the audience view, the document editor, and any material copied into the editor should match.

**Comment by CameronDevine** [comment]
Is there an estimate on when this will be fixed?

**Comment by chrislim** [comment]
We should have a release out this week to address it. It turned out to be a trickier problem than it initially seemed. If after the release you see more problems, just reopen this ticket and attach them.

**Comment by CameronDevine** [comment]
This issue is happening again.
